version: '3.8'

services:
  # Serviço do banco de dados
  db:
    image: postgres:14
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço do backend em Node
  backend:
    container_name: meu-backend-node
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Variáveis usadas pela aplicação (Node)
      DB_HOST: db
      DB_USER: meu_usuario
      DB_PASSWORD: minha_senha
      DB_NAME: meu_banco
      DB_PORT: 5432
      # Se quiser usar outra porta no container, defina ex: PORT=3000
    volumes:
      - ./:/usr/src/app
    command: npm run start:prod

volumes:
  postgres_data:
